---
services:
  db:
    image: shobha722/pyapp:db-image
    ports:
      - "3306:3306"
    deploy:
      replicas: 1
    networks:
      - mynetwork
  auth_service:
    image: shobha722/pyapp:auth-image
    ports:
      - "5001:5001"
    deploy:
      replicas: 1
    networks:
      - mynetwork
    depends_on:
      - db
  book_service:
    image: shobha722/pyapp:book-image
    ports:
      - "5002:5002"
    deploy:
      replicas: 1
    networks:
      - mynetwork
    depends_on:
      - db
  borrow_service:
    image: shobha722/pyapp:borrow-image
    ports:
      - "5003:5003"
    deploy:
      replicas: 1
    networks:
      - mynetwork
    depends_on:
      - db
  frontend_service:
    image:shobha722/pyapp:frontend-image
    ports:
      - "5000:5000"
    deploy:
      replicas: 1
    networks:
      - mynetwork
    depends_on:
      - auth_service
      - book_service
      - borrow_service
networks:
  mynetwork:
    diver: overlay
